ChangeFinance/flutter_ui_kit

- lib/main.dart
- lib/stories/numpads.dart
- lib/text.dart
- lib/widgets/text/numpad_text.dart
- test/widgets/text/numpad_text_test.dart
> Hook 412 Implement NUMPAD from the new UI kit

- lib/main.dart
- lib/stories/progress_indicators.dart
- lib/widgets/bottom_green_progress_indicator.dart
Create a component in the ui lib
See deigns https://app.zeplin.io/project/5c4596fbeb06d337b5b819e2/screen/5ccf18b8441733678aa6f85c
Should display progress based on a % value. (between 0 and 100)
> DOPE-287 Create progress indicator UI component

- lib/main.dart
- lib/stories/password_validators.dart
- lib/widgets/password_validator.dart
- test/widgets/password_validator_test.dart
This component implements the progress indicator widget to display the password strength being used.
> Password validator created with custom colors and strength hints

- lib/widgets/high_popover_modal.dart
- lib/widgets/popover_modal.dart
As the BottomSheet library does not allow the popover modal to change its height i created a new BottomSheet file that has customisable height.
> Created a new BottomSheet alternative that has customizable height.

- lib/main.dart
- lib/widgets.dart
- lib/widgets/custom_date_picker.dart
- pubspec.lock
- pubspec.yaml
Custom date picker for task https://change-finance.atlassian.net/browse/DOPE-166
> DOPE-166 - Date of birth wizard page

- lib/main.dart
- lib/widgets.dart
- lib/widgets/custom_date_picker.dart
- pubspec.yaml
fix issues for task https://change-finance.atlassian.net/browse/DOPE-166
> Dope 166 date of birth wizard page fixes

- lib/stories/graphs.dart
- lib/story_book/prop_updater/dropdown_prop_updater.dart
- lib/widgets/graph.dart
- test/widgets/graph_test.dart
- added lineColor property as a replacement of enableAutoColor property. 
- fixes for issues in dropdown_prop_selector
> Updates to graph component

- lib/stories/layouts.dart
- lib/widgets/layout/titled_generic_template.dart
Added a new page template (it provides the ability to add title, picture and has a scrollable area). It is planed to be used in 'token swap' screens.
> EN-168. Added a template with title, picture and scroll

- lib/widgets/layout/utility_template.dart
> EN-173. Utility template: make container's width restriction optional

- lib/widgets/custom_date_picker.dart
> custom date of birth

- lib/stories/buttons.dart
- lib/stories/info_box.dart
- lib/stories/layouts.dart
- lib/text.dart
- lib/widgets/change_app_icons.dart
- lib/widgets/currency_display.dart
- lib/widgets/currency_switcher.dart
- lib/widgets/layout/app_bar.dart
- lib/widgets/layout/buy_sell_template.dart
- lib/widgets/security_info_box.dart
- lib/widgets/switcher_button.dart
Please review https://change-finance.atlassian.net/browse/EN-302
Related to https://github.com/ChangeFinance/changeapp/pull/616
> Buy sell bugs

- lib/widgets/switcher_button.dart
Please review. changes are made for this task https://change-finance.atlassian.net/browse/EN-308
Switcher button: make label visible depending on the parameter
> switcher button: make label optional

- lib/stories/password_validators.dart
- lib/widgets/password_validator.dart
- test/widgets/password_validator_test.dart
show: "Make it longer than 8 characters."
> If all conditions met but shorter than 8 characters > 

- lib/widgets/text/numpad_text.dart
Please review. A minor change for https://change-finance.atlassian.net/browse/EN-332
> EN-332. added a onKey callback to numpad

- lib/widgets/two_states_button.dart
Please review for https://change-finance.atlassian.net/browse/EN-382
> EN-382. Convert flow fixes

- lib/widgets/layout/custom_flexible_space_bar.dart
- lib/widgets/layout/sliver_template.dart
Reverts ChangeFinance/flutter_ui_kit#129
> Revert "add elevation to sliver app bar"

- lib/widgets/time_frame_selector.dart
Please review https://change-finance.atlassian.net/browse/EN-489
> update time frame

- lib/widgets/high_popover_modal.dart
- lib/widgets/popover_modal.dart
fixes popover modal borders
https://change-finance.atlassian.net/browse/EN-575
Popover modals.
Revert commit.
___
QA Tester: @wtakashi 
Approved: @wtakashi
> - fixed popover modal borders

- lib/widgets/text/passcode_numpad_text.dart
add ability to remove numpad text
(#DOPE-123)
add ability to remove numpad text
Revert commit
___
Owner: @SZdobnikova 
QA Tester: 
Approved:
> https://change-finance.atlassian.net/browse/DOPE-737

- lib/stories/graphs.dart
- lib/widgets/time_frame_selector.dart
- test/widgets/time_frame_selector_test.dart
Adds max time frame functionality for TimeFrameSelector widget.
EN - Mammoth
TimeFrameSelector widget
Revert commit.
___
QA Tester:
Approved: @wtakashi
> EN - added max time frame functionality

- lib/main.dart
- lib/stories/inputs.dart
- lib/widgets/text/email.dart
- test/widgets/text/email_test.dart
Adds email input
EN-712
Adds input type.
Revert commit.
___
QA Tester: 
Approved: @wtakashi
> EN added email input

- lib/stories/cards.dart
- lib/text.dart
- lib/widgets/news/news_card.dart
- test/widgets/news/news_card_test.dart
Adds News Card widget.
EN-711
Adds widfget.
Revert commit.
___
QA Tester:
Approved: @wtakashi
> EN- added News Card

- lib/color.dart
- lib/main.dart
- lib/stories/listItems.dart
- lib/widgets/list_items/transaction_list_item.dart
- test/widgets/list_items/transaction_list_item_test.dart
Added a component for transaction list item.
Used in https://github.com/ChangeFinance/changeapp/pull/1172
En 739. Update tx list screen UI. https://change-finance.atlassian.net/browse/EN-739
Revert commit
___
QA Tester:
Approved:
> En 739. Trx list item widget

- lib/widgets/list_items/transaction_list_item.dart
Fixes minor design issues on transaction list item widget.
EN-739
Transaction list item
Revert commit.
___
QA Tester:
Approved:
> - transaction list item minor changes

- lib/stories/currency_displays.dart
- lib/widgets/currency_switcher.dart
- lib/widgets/layout/swipe_up_to_confirm.dart
Update CurrencySwitcher to show only amount for selected currency
EN-760. BTC market order revisions. https://change-finance.atlassian.net/browse/EN-760
Revert commit
___
QA Tester:
Approved:
> En 629 new pricing

- lib/widgets/list_items/transaction_list_item_container.dart
fix analyzer issues
Revert commit
___
QA Tester:
Approved:
> fix analyzer

- lib/widgets/list_items/transaction_list_item.dart
- test/widgets/list_items/transaction_list_item_test.dart
Trims unnecessary empty spaces from transaction title.
EN - T Rex
Transaction list item.
Revert commit.
___
QA Tester:
Approved:
> EN - trimmed unnecessary empty spaces from transaction title

- lib/widgets/top_movers/top_movers_card.dart
trimmed space between top cards
https://change-finance.atlassian.net/browse/AL-3
trimmed space between top cards
Revert commit
___
Owner: @SZdobnikova 
QA Tester: 
Approved:
> AL-3 Implement Top rising / falling assets

- lib/widgets/layout/swipe_up_to_confirm.dart
small change to take title from outside of widget
https://change-finance.atlassian.net/browse/AL-65
small change to take title from outside of widget
Revert commit
___
Owner: @SZdobnikova 
QA Tester: 
Approved:
> AL-65  Add Swipe Up to confirm to Buy-Sell flow

- lib/stories/top_movers_cards.dart
- lib/widgets/top_movers/top_movers_card.dart
removed margin from top mover card
https://change-finance.atlassian.net/browse/AL-3
removed margin from top mover card
Revert commit
___
Owner: @SZdobnikova 
QA Tester: 
Approved:
> changes for top mover card

- lib/widgets/text/label_text.dart
Change label text fontWeight to normal
(#EN-749)
Font change
Revert commit
___
QA Tester:
> label text fontWeight

- lib/widgets/list_items/transaction_list_item.dart
fix text scaling issue
(#DOPE-123)
___
QA Tester:
Approved:
> fix text scaling issue

- lib/widgets/list_items/transaction_list_item.dart
Fixes transaction list padding.
EN - Rhyniognatha
Transaction list.
Revert commit.
___
Owner:
QA Tester:
Approved:
> - transaction list padding

- lib/widgets/asset_rate.dart
Related to https://github.com/ChangeFinance/changeapp/pull/1231
EN-801. Cryptocurrency EUR values requiring 4 decimal places. https://change-finance.atlassian.net/browse/EN-801
Revert commit
___
QA Tester:
Approved:
> added configurable decimal places to asset_rate component

- lib/stories/pin_views.dart
- lib/widgets/pin_view.dart
- test/widgets/pin_view_test.dart
Added options to PinView component to display entered text and to highlight error
(#EN-847)
Adds new options to existing component
Revert commit
___
Owner: Vadim
QA Tester:
Approved:
> Added options to PinView component

- lib/widgets/layout/utility_template.dart
Used to add back button to Utility template. Related to https://github.com/ChangeFinance/changeapp/pull/1251
EN-935. Fix the design inconsisteny for signed up users. https://change-finance.atlassian.net/browse/EN-935
Revert commit
___
QA Tester:
Approved:
> added ability to imply leading to Utility template

- lib/widgets/list_items/transaction_list_item.dart
For some BTC values the ticker is shown, but not for all. The correct way would be to show the full amount and the ticker together.
EN-887. Ticker is not shown in the tx list. https://change-finance.atlassian.net/browse/EN-887
Revert commit
___
QA Tester:
Approved:
> EN-887. Ticker is not shown in the tx list

- lib/main.dart
- lib/stories/new_typography.dart
- lib/text_styles.dart
- pubspec.yaml
Add new typography 
Revert Commit
___
Owner: Tomi
QA Tester:
Approved:
> Add new typography

- .circleci/config.yml
- lib/widgets/graph.dart
- pubspec.yaml
(#DOPE-123)
___
Owner: Alec
QA Tester: Kaisa
Approved: Bode
> updated Sparkline to use cubic smoothing

- pubspec.yaml
(#DOPE-123)
___
Owner: Alec
QA Tester: Kaisa
Approved: Bode
> Update sparkline version

- lib/widgets/graph.dart
- pubspec.yaml
(#DOPE-123)
___
Owner: Tomi
QA Tester: 
Approved:
> Al revert smoothing

- lib/main.dart
- lib/stories/odometers.dart
- lib/widgets/odometer/odometer.dart
- lib/widgets/odometer/single_digit.dart
- lib/widgets/odometer/text_run.dart
- pubspec.yaml
Create odometer widget.
AL-176
Beautifies the app
Revert commit
___
Owner: Tomi
QA Tester: Saeid
Approved:
> Al 176 odometer widget

- lib/stories/currency_displays.dart
- lib/widgets/asset_rate.dart
- lib/widgets/odometer/odometer.dart
- lib/widgets/odometer/single_digit.dart
- lib/widgets/odometer/text_run.dart
- pubspec.yaml
Add animated asset rate widget
(#DOPE-123)
Beautify the app
Revert commit
___
Owner: Tomi
QA Tester:
Approved:
> Animated asset rate

- lib/widgets/asset_rate.dart
- pubspec.yaml
(#DOPE-123)
___
Owner: Alec
QA Tester: Kaisa
Approved: Bode
> Build hotfix

- lib/widgets/asset_rate.dart
- pubspec.yaml
(#DOPE-123)
___
Owner: Alec
QA Tester: Kaisa
Approved: Bode
> Odometer badge

- lib/widgets/odometer/single_digit.dart
Odometer performance optimisation. 
This PR moves a potentially expensive computation that was previously done in the build method into the initState method. 
N/A
Odometer performance improvement
Revert commit
___
Owner: Tomi
> optimisation for odometer

- lib/widgets/badge/odometer_badge.dart
- lib/widgets/odometer/odometer.dart
- lib/widgets/odometer/single_digit.dart
- lib/widgets/odometer/text_run.dart
Fix bug that occurs in the odometer when the device font size is changed
N/A
Fix odometer bug
Revert commit
___
Owner:
QA Tester:
Approved:
> fix odometer text scaling

- lib/stories/layouts.dart
- lib/widgets/layout/utility_generic_template.dart
- lib/widgets/layout/utility_template.dart
- test/widgets/utility_generic_layout_test.dart
add more generic utility template
Related to EN-1275
EN-1275. Add verification experiment. https://change-finance.atlassian.net/browse/EN-1275
Revert commit
___
Owner:
QA Tester:
Approved:
> add more generic utility template

- lib/widgets/layout/swipe_up_to_confirm.dart
Update swipe up to confirm layout sizing. Update the swipe up handle to reflect updated designs
N/A
UI Update
Revert commit
___
Owner:
QA Tester:
Approved:
> fix swipable screen sizing

- .github/workflows/feature-branch.yml
- pubspec.yaml
(#DOPE-123)
Update dependencies to work with flutter version v1.20.4
Revert commit
___
Owner:
> update flutter svg and version

- lib/widgets/slider/slider.dart
- added onPageChanged to Slider
EN - 1389
Slider widget
Revert commit.
___
QA Tester:
Approved:
> EN - added onPageChanged to Slider

- lib/widgets/custom_date_picker.dart
- added onConfirm callback to CustomDataPicker
EN-1392
CustomDatePicker widget
Revert commit.
___
QA Tester:
Approved:
> EN - added onConfirm callback to CustomDatePicker

- lib/widgets/layout/swipe_up_to_confirm.dart
- Adds onBack callback to swipeable screen
EN-1400
Swipeable screen.
Revert commit.
___
Owner: @mustafatufan
QA Tester:
Approved:
> EN - onBack callback added

- lib/widgets/high_popover_modal.dart
- lib/widgets/popover_modal.dart
Parameterize animation configuration for popup modal
[CFD-734](https://change-finance.atlassian.net/browse/CFD-734)
Required for fast transfer
Revert commit
___
Owner:
> parameterize animation configuration for popup modal

- lib/stories/badges.dart
- lib/widgets/badge/category_badge.dart
- lib/widgets/badge/category_badge_list.dart
- test/widgets/cagegory_badge_list_test.dart
- test/widgets/cagegory_badge_test.dart
EN-1896 Create tab categories component
(#EN-1896)
Revert commit
> EN-1896 Create tab categories component
